repos:
- repo: git@github.com:pre-commit/pre-commit-hooks
  sha: v1.2.3
  hooks:
    - id: check-case-conflict
    - id: fix-encoding-pragma
    - id: check-docstring-first
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-ast
    - id: check-byte-order-marker
    - id: check-merge-conflict
    - id: detect-private-key
    - id: mixed-line-ending
